In [585]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [586]:
cd C:\Users\yashv\Desktop\Projects

C:\Users\yashv\Desktop\Projects

## Part-1: Data Exploration and Pre-processing

In [587]:
# 1) Load the given dataset

In [588]:
data=pd.read_csv("ML Project 8 - ML Linear Regression Home Price Prediction & Analysis.txt")

In [589]:
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [590]:
#2) Print all the column names
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [591]:
#3) Describe the data
data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [592]:
#4) Drop address, date, postcode, YearBuilt, lattitude, longtitude columns

In [593]:
data.drop(["Address","Date","Postcode","YearBuilt","Lattitude","Longtitude"],axis=1,inplace=True)

In [594]:
data.head(2)

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0

In [595]:
#5) Find the count of null value in each column

In [596]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

In [597]:
#6) Fill the null value of property count, distance, Bedroom2, Bathroom, Car with 0

In [598]:
data[["Propertycount","Distance","Bedroom2","Bathroom","Car"]]=data[["Propertycount","Distance","Bedroom2","Bathroom","Car"]].fillna(0)

In [599]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0

In [600]:
#7) Fill Null value of land size and bidding area columns with Mean

In [601]:
data[["Landsize","BuildingArea"]]=data[["Landsize","BuildingArea"]].fillna(data[["Landsize","BuildingArea"]].mean())

In [602]:
#8) Find the unique value in method column

In [603]:
data["Method"].unique()

array(['SS', 'S', 'VB', 'SP', 'PI', 'SN', 'W', 'PN', 'SA'], dtype=object)

In [604]:
#9) Create a dummy data for categorical data

In [605]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,6543.0

In [606]:
data["Suburb"].unique() #label encoding

array(['Abbotsford', 'Airport West', 'Albert Park', 'Alphington',
       'Altona', 'Altona North', 'Armadale', 'Ascot Vale', 'Ashburton',
       'Ashwood', 'Avondale Heights', 'Balaclava', 'Balwyn',
       'Balwyn North', 'Bentleigh', 'Bentleigh East', 'Box Hill',
       'Braybrook', 'Brighton', 'Brighton East', 'Brunswick',
       'Brunswick West', 'Bulleen', 'Burwood', 'Camberwell', 'Canterbury',
       'Carlton North', 'Carnegie', 'Caulfield', 'Caulfield North',
       'Caulfield South', 'Chadstone', 'Clifton Hill', 'Coburg',
       'Coburg North', 'Collingwood', 'Doncaster', 'Eaglemont',
       'Elsternwick', 'Elwood', 'Essendon', 'Essendon North', 'Fairfield',
       'Fitzroy', 'Fitzroy North', 'Flemington', 'Footscray', 'Glen Iris',
       'Glenroy', 'Gowanbrae', 'Hadfield', 'Hampton', 'Hampton East',
       'Hawthorn', 'Heidelberg Heights', 'Heidelberg West', 'Hughesdale',
       'Ivanhoe', 'Kealba', 'Keilor East', 'Kensington', 'Kew',
       'Kew East', 'Kooyong', 'Maidstone', 'Malvern', 'Malvern East',
       'Maribyrnong', 'Melbourne', 'Middle Park', 'Mont Albert',
       'Moonee Ponds', 'Moorabbin', 'Newport', 'Niddrie',
       'North Melbourne', 'Northcote', 'Oak Park', 'Oakleigh South',
       'Parkville', 'Pascoe Vale', 'Port Melbourne', 'Prahran', 'Preston',
       'Reservoir', 'Richmond', 'Rosanna', 'Seddon', 'South Melbourne',
       'South Yarra', 'Southbank', 'Spotswood', 'St Kilda', 'Strathmore',
       'Sunshine', 'Sunshine North', 'Sunshine West', 'Surrey Hills',
       'Templestowe Lower', 'Thornbury', 'Toorak', 'Viewbank', 'Watsonia',
       'West Melbourne', 'Williamstown', 'Williamstown North', 'Windsor',
       'Yallambie', 'Yarraville', 'Aberfeldie', 'Bellfield',
       'Brunswick East', 'Burnley', 'Campbellfield', 'Carlton',
       'East Melbourne', 'Essendon West', 'Fawkner', 'Hawthorn East',
       'Heidelberg', 'Ivanhoe East', 'Jacana', 'Kingsbury', 'Kingsville',
       'Murrumbeena', 'Ormond', 'West Footscray', 'Albion', 'Brooklyn',
       'Glen Huntly', 'Oakleigh', 'Ripponlea', 'Cremorne', 'Docklands',
       'South Kingsville', 'Strathmore Heights', 'Travancore',
       'Caulfield East', 'Seaholme', 'Keilor Park', 'Gardenvale',
       'Princes Hill', 'Altona Meadows', 'Ardeer', 'Attwood', 'Bayswater',
       'Bayswater North', 'Beaumaris', 'Berwick', 'Blackburn',
       'Blackburn South', 'Boronia', 'Briar Hill', 'Broadmeadows',
       'Bundoora', 'Burnside Heights', 'Burwood East', 'Cairnlea',
       'Caroline Springs', 'Cheltenham', 'Clarinda', 'Clayton',
       'Clyde North', 'Craigieburn', 'Cranbourne', 'Croydon',
       'Croydon Hills', 'Croydon North', 'Dandenong', 'Dandenong North',
       'Diamond Creek', 'Dingley Village', 'Doncaster East', 'Donvale',
       'Doreen', 'Edithvale', 'Eltham', 'Eltham North', 'Emerald',
       'Epping', 'Eumemmerring', 'Ferntree Gully', 'Forest Hill',
       'Frankston', 'Frankston North', 'Frankston South', 'Gisborne',
       'Gladstone Park', 'Glen Waverley', 'Greensborough', 'Greenvale',
       'Hallam', 'Healesville', 'Heathmont', 'Highett', 'Hillside',
       'Hoppers Crossing', 'Huntingdale', 'Keilor Downs', 'Keilor Lodge',
       'Keysborough', 'Kings Park', 'Lalor', 'Lower Plenty', 'Lynbrook',
       'MacLeod', 'Melton', 'Melton South', 'Melton West', 'Mentone',
       'Mernda', 'Mickleham', 'Mill Park', 'Mitcham', 'Montmorency',
       'Montrose', 'Mordialloc', 'Mount Waverley', 'Mulgrave',
       'Narre Warren', 'Noble Park', 'Nunawading', 'Oakleigh East',
       'Parkdale', 'Point Cook', 'Ringwood', 'Ringwood East', 'Rockbank',
       'Rowville', 'Roxburgh Park', 'Sandringham', 'Seabrook', 'Seaford',
       'Skye', 'South Morang', 'Springvale', 'Springvale South',
       'St Albans', 'St Helena', 'Sunbury', 'Sydenham', 'Tarneit',
       'Taylors Hill', 'Taylors Lakes', 'Tecoma', 'Templestowe',
       'The Basin', 'Thomastown', 'Truganina', 'Tullamarine', 'Vermont',
       'Vermont South', 'Wantirna', 'Wantirna South', 'Werribee',
       'Werribee South', 'Westmeadows', 'Williams Landing', 'Wollert',
       'Wyndham Vale', 'Aspendale', 'Black Rock', 'Blackburn North',
       'Bonbeach', 'Carrum', 'Chelsea', 'Clayton South', 'Dallas',
       'Delahey', 'Doveton', 'McKinnon', 'Mooroolbark', 'Pakenham',
       'Ringwood North', 'Scoresby', 'Warrandyte', 'Watsonia North',
       'Wattle Glen', 'Wheelers Hill', 'Albanvale', 'Aspendale Gardens',
       'Belgrave', 'Carrum Downs', 'Cranbourne East', 'Cranbourne North',
       'Deer Park', 'Heatherton', 'Kilsyth', 'Langwarrin', 'Notting Hill',
       'Patterson Lakes', 'Riddells Creek', 'Beaconsfield Upper',
       'Chelsea Heights', 'Chirnside Park', 'Coolaroo', 'Darley',
       'Hampton Park', 'Keilor', 'Meadow Heights', 'Mount Evelyn',
       'North Warrandyte', 'Sandhurst', 'Silvan', 'Wallan',
       'Croydon South', 'Derrimut', 'Diggers Rest', 'Knoxfield', 'Upwey',
       'Warranwood', 'Bacchus Marsh', 'Bullengarook', 'Deepdene',
       'Hurstbridge', 'Kurunjang', 'Laverton', 'Lilydale', 'Wonga Park',
       'Endeavour Hills', 'Officer', 'Olinda', 'Waterways',
       'Beaconsfield', 'Yarra Glen', 'Brookfield', 'Lysterfield',
       'Plenty', 'Whittlesea', 'Burnside', 'New Gisborne', 'Guys Hill',
       'Plumpton', 'croydon', 'Monbulk', 'Avonsleigh', 'Wildwood',
       'Gisborne South', 'Research', 'viewbank', 'Botanic Ridge', 'Bulla',
       'Coldstream', 'Hopetoun Park', 'Cranbourne West', 'Eynesbury',
       'Fawkner Lot', 'Ferny Creek', 'Wandin North', 'Kalkallo',
       'Menzies Creek'], dtype=object)

In [607]:
from sklearn.preprocessing import LabelEncoder

In [608]:
encoder=LabelEncoder()

In [609]:
#data["Suburb"]=encoder.fit_transform(data['Suburb'])

In [610]:
data=pd.get_dummies(data,columns=["Suburb"])

In [611]:
data.isnull().sum()

Rooms                   0
Type                    0
Price                7610
Method                  0
SellerG                 0
                     ...
Suburb_Yallambie        0
Suburb_Yarra Glen       0
Suburb_Yarraville       0
Suburb_croydon          0
Suburb_viewbank         0
Length: 365, dtype: int64

In [612]:
data = data.dropna(subset=["Price"])

In [613]:
data

,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,...,Suburb_Williamstown North,Suburb_Windsor,Suburb_Wollert,Suburb_Wonga Park,Suburb_Wyndham Vale,Suburb_Yallambie,Suburb_Yarra Glen,Suburb_Yarraville,Suburb_croydon,Suburb_viewbank
1,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,...,False,False,False,False,False,False,False,False,False,False
2,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,...,False,False,False,False,False,False,False,False,False,False
4,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,...,False,False,False,False,False,False,False,False,False,False
5,3,h,850000.0,PI,Biggin,2.5,3.0,2.0,1.0,94.000000,...,False,False,False,False,False,False,False,False,False,False
6,4,h,1600000.0,VB,Nelson,2.5,3.0,1.0,2.0,120.000000,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,...,False,False,False,False,False,False,False,True,False,False
34853,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,...,False,False,False,False,False,False,False,True,False,False
34854,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,...,False,False,False,False,False,False,False,True,False,False
34855,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,...,False,False,False,False,False,False,False,True,False,False
34856,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,...,False,False,False,False,False,False,False,True,False,False

In [614]:
data["Type"].unique()

array(['h', 't', 'u'], dtype=object)

In [615]:
data=pd.get_dummies(data,columns=["Type"])

In [616]:
data

,Rooms,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,...,Suburb_Wonga Park,Suburb_Wyndham Vale,Suburb_Yallambie,Suburb_Yarra Glen,Suburb_Yarraville,Suburb_croydon,Suburb_viewbank,Type_h,Type_t,Type_u
1,2,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,...,False,False,False,False,False,False,False,True,False,False
2,2,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,...,False,False,False,False,False,False,False,True,False,False
4,3,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,...,False,False,False,False,False,False,False,True,False,False
5,3,850000.0,PI,Biggin,2.5,3.0,2.0,1.0,94.000000,160.2564,...,False,False,False,False,False,False,False,True,False,False
6,4,1600000.0,VB,Nelson,2.5,3.0,1.0,2.0,120.000000,142.0000,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,...,False,False,False,False,True,False,False,True,False,False
34853,2,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,...,False,False,False,False,True,False,False,True,False,False
34854,2,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,...,False,False,False,False,True,False,False,False,True,False
34855,3,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,...,False,False,False,False,True,False,False,True,False,False
34856,2,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,...,False,False,False,False,True,False,False,True,False,False

In [617]:
data["Method"].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [618]:
data=pd.get_dummies(data,columns=["Method"])

In [619]:
data

,Rooms,Price,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,...,Suburb_croydon,Suburb_viewbank,Type_h,Type_t,Type_u,Method_PI,Method_S,Method_SA,Method_SP,Method_VB
1,2,1480000.0,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,...,False,False,True,False,False,False,True,False,False,False
2,2,1035000.0,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,...,False,False,True,False,False,False,True,False,False,False
4,3,1465000.0,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,...,False,False,True,False,False,False,False,False,True,False
5,3,850000.0,Biggin,2.5,3.0,2.0,1.0,94.000000,160.2564,Yarra City Council,...,False,False,True,False,False,True,False,False,False,False
6,4,1600000.0,Nelson,2.5,3.0,1.0,2.0,120.000000,142.0000,Yarra City Council,...,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,...,False,False,True,False,False,True,False,False,False,False
34853,2,888000.0,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,...,False,False,True,False,False,False,False,False,True,False
34854,2,705000.0,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,...,False,False,False,True,False,False,True,False,False,False
34855,3,1140000.0,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,...,False,False,True,False,False,False,False,False,True,False
34856,2,1020000.0,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,...,False,False,True,False,False,True,False,False,False,False

In [620]:
data=data.drop_duplicates()

In [621]:
data

,Rooms,Price,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,...,Suburb_croydon,Suburb_viewbank,Type_h,Type_t,Type_u,Method_PI,Method_S,Method_SA,Method_SP,Method_VB
1,2,1480000.0,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,...,False,False,True,False,False,False,True,False,False,False
2,2,1035000.0,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,...,False,False,True,False,False,False,True,False,False,False
4,3,1465000.0,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,...,False,False,True,False,False,False,False,False,True,False
5,3,850000.0,Biggin,2.5,3.0,2.0,1.0,94.000000,160.2564,Yarra City Council,...,False,False,True,False,False,True,False,False,False,False
6,4,1600000.0,Nelson,2.5,3.0,1.0,2.0,120.000000,142.0000,Yarra City Council,...,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,...,False,False,True,False,False,True,False,False,False,False
34853,2,888000.0,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,...,False,False,True,False,False,False,False,False,True,False
34854,2,705000.0,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,...,False,False,False,True,False,False,True,False,False,False
34855,3,1140000.0,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,...,False,False,True,False,False,False,False,False,True,False
34856,2,1020000.0,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,...,False,False,True,False,False,True,False,False,False,False

In [622]:
data["SellerG"].unique()

array(['Biggin', 'Nelson', 'Jellis', 'Dingle', 'Purplebricks', 'Greg',
       'LITTLE', 'Collins', 'Kay', 'Beller', 'Marshall', 'hockingstuart',
       'Brad', 'Maddison', 'Barry', 'Airport', 'Considine', 'Rendina',
       'Ray', 'Propertyau', 'McDonald', 'Frank', 'Prof.', 'Harcourts',
       'Thomson', 'Buxton', 'RT', "Sotheby's", 'Cayzer', 'Chisholm',
       'Brace', 'Miles', 'Holland', 'McGrath', 'Love', 'Thomas', 'Barlow',
       'Sweeney', 'Village', 'Jas', 'Williams', 'Gunn&Co', 'Burnham',
       'Compton', 'FN', 'Hunter', 'Raine&Horne', 'Noel', 'Hodges', 'Gary',
       'Fletchers', 'Woodards', 'Raine', 'Alexkarbon', 'Walshe', 'Weda',
       'Stockdale', 'Tim', 'AIME', 'Moonee', 'HAR', 'Edward', 'Philip',
       'RW', 'North', 'MICM', 'Ascend', 'Christopher', 'Morrison',
       'Mandy', 'R&H', 'Fletchers/One', 'Lindellas', 'Appleby', 'Assisi',
       'One', 'Owen', 'Parkes', 'C21', "O'Brien", 'Bayside', 'Paul',
       'hockingstuart/Buxton', 'First', 'Matthew', 'Melbourne',
       'Anderson', 'Nick', 'Allens', 'Bells', 'Trimson', 'Douglas',
       'Batty', 'GL', 'YPA', "Tiernan's", 'J', 'Rodney', 'Joseph',
       'Harrington', 'Galldon', 'Chambers', 'Peter', 'Grantham',
       'hockingstuart/Advantage', 'Garvey', "O'Donoghues", 'Hamilton',
       'Bekdon', 'Ross', 'Weast', 'Century', 'Kelly', 'Property',
       "Private/Tiernan's", 'Australian', 'Bustin', "Abercromby's",
       'Castran', 'iTRAK', 'Del', 'Nicholson', 'JMRE', 'ASL', 'Re', 'RE',
       'Ham', 'Darren', 'Vic', 'Scott', 'Pride', 'Morleys', 'Wilson',
       'Buxton/Advantage', 'Whiting', 'Pagan', 'Joe', 'Red', 'Caine',
       'Naison', 'Sweeney/Advantage', 'Nguyen', 'Domain', 'Eview',
       'Jason', 'Professionals', "D'Aprano", 'Charlton', 'CASTRAN',
       'Wood', 'Haughton', 'William', 'Coventry', 'Buckingham',
       'Nardella', 'Reach', 'Walsh', 'Karen', 'LJ', 'Direct',
       'Fletchers/Fletchers', 'Besser', 'Johnston', 'Redina', 'Clairmont',
       'Changing', 'Lucas', 'Elite', 'Buxton/Find', 'W.B.', 'Leased',
       'Win', 'New', 'Geoff', 'hockingstuart/Barry', 'Blue', 'Steveway',
       'Dixon', 'Parkinson', 'VICPROP', 'Meadows', 'Allan', 'S&L',
       'Crane', 'Calder', 'Homes', 'Zahn', 'Mason', 'David', 'Luxe',
       'Prowse', 'Ken', 'iOne', 'hockingstuart/Village', 'Iconek',
       'Luxton', 'Hooper', 'Oak', 'White', 'Weston', 'Reed', 'Oriental',
       'Craig', 'Max', 'Rosin', 'Steller', 'Real', 'Hall', 'Icon',
       'buyMyplace', 'Collings', 'WHITEFOX', 'Metro', '@Realty',
       'Hoskins', 'Gardiner', 'McLennan', 'Triwest', 'PRDNationwide',
       'Only', 'Leyton', 'Obrien', 'Maitland', 'Reliance', 'Rounds',
       'Millership', 'iSell', 'L', 'Ash', 'Jim', 'Ace', 'Flannagan',
       'JRW', 'Carter', 'M.J', 'iProperty', 'Hayeswinckle', 'Schroeder',
       'iHomes', 'VICProp', 'REMAX', 'Space', 'Victory', 'Aumeca',
       'Smart', 'Mindacom', 'Ryder', 'Asset', 'LLC', 'Sell', 'Mitchell',
       'U', 'Nicholas', 'Keatings', 'Aquire', 'Conquest', 'Rombotis',
       'Prime', 'Donovan', 'Community', 'Free', 'Veitch', 'Peake',
       'Ristic', 'Upper', 'Daniel', 'Xynergy', 'VicHomes', 'Westside',
       'Leeburn', 'TRUE', 'Leading', 'Bullen', 'Better', 'Langwell',
       'Kaye', 'Nicholls', 'Bowman', 'Boutique', 'Just', 'Home',
       'McNaughton', 'Black', 'The', 'Open', 'Darras', 'Roger', 'Follett',
       'Le', 'McEwing', 'Sandhurst', 'Avion', 'Boran',
       'hockingstuart/hockingstuart', 'Area', 'MJ', 'Eric', 'SN', 'P',
       'PRD', 'Bombay', 'Quinta', 'T', 'Rexhepi', 'Point', 'LJH', 'Munn',
       'Justin', 'Blackbird', 'Sweeney/Burnham', 'H', 'Branon', 'Alex',
       'Benchmark', 'Gellibrand', 'hockingstuart/Harcourts', 'Charter',
       'Surreal', 'Upside', 'OBrien', 'Meallin', 'JY', 'Mark', 'For',
       'Leaders', 'Shape', 'McGrath/Langwell', 'Benlor', 'Burns',
       'K.R.Peters', 'Buxton/Buxton', 'Buxton/Marshall', 'CarlinSmith',
       'hockingstuart/Sweeney', 'People', 'hockingstuart/Biggin', 'Mega',
       'Skad', 'Wyndham', 'Create', 'Janice', 'G&H', 'Commercial', 'PSP',
       'Unity', 'hockingstuart/Marshall', 'McGrath/First', 'Spencer',
       'Sanctuary'], dtype=object)

In [623]:
data=pd.get_dummies(data,columns=["SellerG"])

In [624]:
data

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,...,SellerG_hockingstuart/Harcourts,SellerG_hockingstuart/Marshall,SellerG_hockingstuart/Sweeney,SellerG_hockingstuart/Village,SellerG_hockingstuart/hockingstuart,SellerG_iHomes,SellerG_iOne,SellerG_iProperty,SellerG_iSell,SellerG_iTRAK
1,2,1480000.0,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,...,False,False,False,False,False,False,False,False,False,False
2,2,1035000.0,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,...,False,False,False,False,False,False,False,False,False,False
4,3,1465000.0,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,...,False,False,False,False,False,False,False,False,False,False
5,3,850000.0,2.5,3.0,2.0,1.0,94.000000,160.2564,Yarra City Council,Northern Metropolitan,...,False,False,False,False,False,False,False,False,False,False
6,4,1600000.0,2.5,3.0,1.0,2.0,120.000000,142.0000,Yarra City Council,Northern Metropolitan,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,...,False,False,False,False,False,False,False,False,False,False
34853,2,888000.0,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,...,False,False,False,False,False,False,False,False,False,False
34854,2,705000.0,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,...,False,False,False,False,False,False,False,False,False,False
34855,3,1140000.0,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,...,False,False,False,False,False,False,False,False,False,False
34856,2,1020000.0,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,...,False,False,False,False,False,False,False,False,False,False

In [625]:
data["Regionname"].unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria', nan], dtype=object)

In [626]:
data=pd.get_dummies(data,columns=["Regionname"])

In [627]:
data

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Propertycount,...,SellerG_iSell,SellerG_iTRAK,Regionname_Eastern Metropolitan,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1480000.0,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,4019.0,...,False,False,False,False,True,False,False,False,False,False
2,2,1035000.0,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,4019.0,...,False,False,False,False,True,False,False,False,False,False
4,3,1465000.0,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,4019.0,...,False,False,False,False,True,False,False,False,False,False
5,3,850000.0,2.5,3.0,2.0,1.0,94.000000,160.2564,Yarra City Council,4019.0,...,False,False,False,False,True,False,False,False,False,False
6,4,1600000.0,2.5,3.0,1.0,2.0,120.000000,142.0000,Yarra City Council,4019.0,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,6543.0,...,False,False,False,False,False,False,False,False,True,False
34853,2,888000.0,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,6543.0,...,False,False,False,False,False,False,False,False,True,False
34854,2,705000.0,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,6543.0,...,False,False,False,False,False,False,False,False,True,False
34855,3,1140000.0,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,6543.0,...,False,False,False,False,False,False,False,False,True,False
34856,2,1020000.0,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,6543.0,...,False,False,False,False,False,False,False,False,True,False

In [628]:
data=pd.get_dummies(data,columns=["CouncilArea"])

## Part-2: Working with Model

In [629]:
# 1) Create the target data and feature data where target data is price

In [630]:
x=data.drop("Price",axis=1)
y=data["Price"]

In [631]:
from sklearn.model_selection import train_test_split

In [632]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [633]:
#scaling

In [634]:
from sklearn.preprocessing import StandardScaler

In [635]:
scaler=StandardScaler()

In [636]:
x_train=pd.DataFrame(scaler.fit_transform(x_train),columns=x.columns)
x_test=pd.DataFrame(scaler.transform(x_test),columns=x.columns)

In [637]:
from sklearn.linear_model import LinearRegression

In [638]:
model=LinearRegression()

In [639]:
model.fit(x_train,y_train)

LinearRegression()

In [640]:
model.score(x_train,y_train)

0.6796039037769162

In [641]:
model.score(x_test,y_test)

0.6732475452165181

In [642]:
data

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Abbotsford,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,2,1480000.0,2.5,2.0,1.0,1.0,202.000000,160.2564,4019.0,True,...,False,False,False,False,False,False,False,False,True,False
2,2,1035000.0,2.5,2.0,1.0,0.0,156.000000,79.0000,4019.0,True,...,False,False,False,False,False,False,False,False,True,False
4,3,1465000.0,2.5,3.0,2.0,0.0,134.000000,150.0000,4019.0,True,...,False,False,False,False,False,False,False,False,True,False
5,3,850000.0,2.5,3.0,2.0,1.0,94.000000,160.2564,4019.0,True,...,False,False,False,False,False,False,False,False,True,False
6,4,1600000.0,2.5,3.0,1.0,2.0,120.000000,142.0000,4019.0,True,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,6.3,4.0,1.0,3.0,593.000000,160.2564,6543.0,False,...,False,False,False,False,False,False,False,False,False,False
34853,2,888000.0,6.3,2.0,2.0,1.0,98.000000,104.0000,6543.0,False,...,False,False,False,False,False,False,False,False,False,False
34854,2,705000.0,6.3,2.0,1.0,2.0,220.000000,120.0000,6543.0,False,...,False,False,False,False,False,False,False,False,False,False
34855,3,1140000.0,6.3,0.0,0.0,0.0,593.598993,160.2564,6543.0,False,...,False,False,False,False,False,False,False,False,False,False
34856,2,1020000.0,6.3,2.0,1.0,0.0,250.000000,103.0000,6543.0,False,...,False,False,False,False,False,False,False,False,False,False

In [643]:
yp=model.predict(x_test)

In [646]:
print("coef:-",model.coef_)
print("intercept_:-",model.intercept_)

coef:- [ 2.54395312e+05 -3.35702162e+05 -1.39671248e+05  1.24482926e+05
  4.43723956e+04  7.83335201e+03  1.11335809e+04  3.63488519e+04
 -4.42443330e+03  1.44374310e+04 -2.34973421e+03 -2.52425623e+03
  1.74420723e+04  1.64513177e+03  1.25265321e+04  7.23389865e+03
 -4.66913384e+03 -1.50505095e+04 -3.10501137e+03  1.53832192e+04
 -1.18910564e+04 -8.52184628e+03 -4.22552441e+03  8.75260249e+03
 -1.19906504e+03 -2.52285662e+03 -1.54096684e+04  2.03726813e-10
  3.65471219e+03 -3.62302708e+03  4.87145642e+02 -1.51709641e+04
  8.50065960e+03  3.21544044e+03  3.49179973e+03  1.89465823e+03
  1.93177310e+04  4.11091605e-10 -5.77253969e+03  9.09952612e+03
 -2.27936747e+03  9.53328112e+03  1.57612689e+04  1.03267003e+04
 -2.90439272e+03  4.06572334e+01  1.09974020e+04  8.71986202e+03
 -8.36735126e-11  1.43232759e+04  1.48551279e+03  3.84924444e+02
  5.16619902e+04  2.34619435e+03 -5.98513141e+03  7.68895625e+02
  1.38195033e+03 -8.15352196e+03 -2.75279998e+03 -6.17659021e+03
  8.86757334e-12 -6.08722282e+03  8.80210143e+03 -1.15275176e+04
  3.73316595e+01 -4.50823131e+03 -5.93495414e+03 -9.80137431e+03
  1.66423885e+03 -4.76880050e+03 -1.29775867e+04 -4.34765756e+03
  2.28886622e+04  5.16026425e+03  1.77065425e+04  1.44004285e+03
 -8.14171642e+03  1.80566728e+04  2.88928139e+03 -4.80925228e+03
  2.27907079e+02  1.63888061e+03  1.48572026e+02 -6.32900720e+03
  1.83655630e+04  1.94597349e+03 -6.17921610e+03  1.29096476e+03
 -2.82562823e+03  4.72130166e+03  4.15898595e+02  7.25508723e+03
  5.58112694e+03 -1.38660001e+04 -1.31614728e+04  1.03728352e+03
 -2.54237236e+03 -1.92682508e+03 -1.17027030e+04  4.97606695e+03
  1.76306456e+03  9.17035871e+02  2.97794136e+03 -1.73437457e+03
  5.60267186e+03 -3.02304591e+02  3.03745942e+03  4.35262482e+03
 -1.10879850e+04  6.47441762e+03  6.12311769e+02  1.17034844e+03
  3.71009121e+03 -5.25120017e+03 -9.12644408e+02 -5.58421253e+03
 -1.08065011e+01  3.52391897e+03  7.45422822e+02 -3.11083929e+03
  9.37501920e+03  8.43766145e+03  7.07734265e+03 -4.12988642e+03
 -2.46259878e+02  1.74228924e+04  1.33291882e+04  1.76321827e+04
  3.69778138e+03  5.08324875e+03 -2.97323138e+03  3.22573408e+03
  6.23294312e+03 -1.34426395e+03 -4.89698079e+02  1.09275639e+04
  2.13235793e+03 -4.92343198e+02  2.14709982e+02  1.87836127e+03
  7.44562274e+03 -8.68224073e+03 -6.43349280e+03  1.10959391e+04
  1.65489766e+03  1.00896299e+04  1.35207655e+04 -4.50129698e+03
  6.81250425e+03 -2.57253153e+02  1.89698023e+04  5.92292654e+03
  1.88898952e+04 -2.76286385e+03  1.54645073e+04  6.19268986e+03
 -1.03016434e+04 -7.07398781e+02 -2.70574779e+04  2.26262777e+04
 -1.35638333e+04 -6.03415304e+03  1.78306748e+03 -1.80468621e+01
  1.27329258e-11 -8.56389464e+03  6.52143788e+03  2.99928055e+04
 -3.36354687e+03  2.34638615e+03 -5.43858821e+04 -2.38237950e+04
  7.83993797e+03 -5.55254726e+01  5.27235134e+03 -1.86869474e+03
 -1.59355284e+04 -2.24851180e+04  3.22942776e+03 -2.76449145e+03
  6.36646291e-12 -5.28464397e+03  9.12292208e+02 -1.82170606e+03
  5.92209303e+02  6.44974002e+03  2.48931708e+04 -6.39828766e+03
  1.56520779e+03 -6.50515801e+03  1.97560486e+03 -4.48040183e+03
 -3.01197793e+03 -6.13346646e+02 -4.05488723e+03 -6.87496479e+03
 -2.89296588e+04 -1.56977335e+04  3.10063851e+03  6.42779131e+03
 -3.08000743e+03  3.28139235e+02  1.01743393e+04 -1.70827682e+02
 -1.14803727e+03  2.42873447e+03 -5.09795869e+03  8.49661308e+03
 -1.95570656e+03  7.60732599e+02  2.56559472e+03  3.16167583e+03
  1.72822892e+03  4.80423874e+03  5.59449959e+03  3.37878228e+04
  9.94698414e+03  9.61483095e+03  9.10129980e+03 -4.65130365e+03
 -3.53534121e+03  4.65002804e+03  6.40899527e+03  2.03674536e+03
  1.39294953e+04  2.04636308e-11  9.67150355e+03 -2.90822405e+02
  2.91382910e+04 -7.33671695e+03  6.92405481e+03  1.83863680e+03
 -4.29452604e+02  2.13655496e+03  3.63797881e-12  6.26100842e+03
 -9.00925389e+03  1.79862655e+02  1.68183235e+04  2.77680319e+03
  1.81397070e+04  3.81745613e+03  1.87097900e+03  4.82002318e+03
  5.11940450e+03 -8.77401644e+03  8.96950497e+03  2.96520800e+03
 -3.35314361e+03  5.07376459e+03  1.65465392e+04  8.23999616e+02
  6.25466759e+03  2.85724836e+03 -2.44520973e+03 -2.98936365e+03
 -1.32206241e+04  2.82302128e+03 -4.91127139e-11  1.01676656e+04
  9.35269686e+03  2.13363312e+04  1.33489630e+04 -8.69930865e+03
  5.41313011e+03  1.97430412e+03  4.05301643e+03 -1.63511304e+04
 -8.80163217e+03 -1.95602261e+04 -1.32403412e+04  9.67437905e+03
  2.24310761e+03 -2.57250421e+04 -1.12548402e+04  9.15093771e+03
  5.82733191e+03  6.49116629e+03  1.00811602e+03 -1.45525923e+03
  3.81865215e+03 -6.18686553e+03 -2.66591553e+03 -4.84976262e+03
  4.54843637e+02  1.71808602e+04  4.64065711e+03 -2.64464639e+03
  1.27887506e+04  1.13749952e+03  1.01580774e+04  5.54245891e+03
  1.50540184e+03 -3.98824879e+03 -1.15284285e+04 -3.46796838e+03
 -1.66400290e+04 -2.03052514e+04 -5.22348220e+03 -2.09270637e+02
 -1.13569416e+03 -4.08451578e+03 -4.16352459e+03 -1.73282879e+04
  8.52904276e+03 -3.42388648e+03  3.47489852e+04 -1.83504395e+03
 -9.16828763e+03 -1.64110126e+04 -9.00500751e+03  4.53344123e+02
 -3.16506395e+03 -5.04924892e+03 -6.00013084e+03  1.41659355e+03
  9.63555724e+03 -6.01713997e+03  4.31361538e+03 -2.25370843e+03
  5.43963753e+03  1.51887192e+04  9.02542922e+02 -1.62782610e+03
 -2.56698618e+02  2.41417608e+03  1.23907815e+03  1.30300699e+03
 -1.33650877e+04  6.93035862e+03  3.05074719e+03 -7.83909752e+03
 -6.43405604e+03  7.92729573e+03 -1.14848906e+03  1.27059810e+03
  4.96943343e+03 -2.72071555e+03 -2.61479727e-11 -1.89565857e+04
 -6.39103502e+02  6.02016537e+03  2.99461475e+03 -4.08388207e+03
 -1.83044962e+03  4.65679523e+03  3.14246112e+03 -1.21669912e+03
  1.85009404e+04 -1.43833056e+03 -6.29490850e+03  8.55190616e+03
  3.61132613e+03  1.68664127e+04 -3.33454379e+03  1.64786299e+03
  1.58100906e+04 -1.81898940e-11  2.75021900e+02  1.04412909e+05
 -1.73881549e+04 -1.05540784e+05 -1.40206990e+04  1.62625233e+04
  4.12554631e+02 -1.31709393e+03 -9.58073772e+03 -2.47476753e+03
 -1.00888753e+03  2.62676258e+02  6.85117793e+03  2.59527850e+03
 -2.55446270e+03  2.44896553e+03  2.00548431e+02 -1.51849322e+03
 -2.33025501e+03 -2.95526633e+02 -2.42758514e+03  2.45537503e+03
  8.10031408e+02 -1.70280998e+03 -2.47507630e+03 -1.34074841e+03
  3.39141043e+03  4.11928453e+02 -9.05168938e+02  2.26436718e+03
  2.65473306e+03 -7.03500247e+03  3.63797881e-12 -2.25215102e+03
 -2.16214903e+03 -5.71919642e+03 -2.44891287e+03  9.79759784e+02
 -1.22042965e+02 -3.08526108e+03  1.81898940e-11 -1.88009871e+03
  6.04638896e+02 -1.39049104e+02  4.99492198e+03  1.89440085e+02
 -1.46245746e+03  4.11713750e+02 -3.65066171e+03 -3.38515991e+03
 -1.90673665e+03  1.75304788e+02  8.68461458e+02 -2.02744465e+03
  1.55043860e+03 -2.00088834e-11  1.09139364e-11 -3.98255046e+03
 -1.56152170e+03  1.61718312e+03  1.86356698e+03 -2.13607239e+03
 -4.10763412e+03  3.63797881e-12  1.32807029e+04 -1.21973031e+02
  4.88388277e+02  2.64870053e+03  1.57184897e+04 -6.52166547e+02
 -4.78252068e+02  9.12546789e+02 -2.02311987e+03  7.78739306e+01
 -3.01380082e+03 -7.78422277e+02 -3.60455828e+03  1.28089733e+03
 -1.21627365e+03  7.70968077e+03  8.64019967e-12  1.96708966e+03
  2.46426994e+03  1.34748712e+03 -7.08974853e+03 -1.82889416e+03
 -6.00820166e+02  3.71964586e+02 -1.46468988e+02 -1.07293147e+03
 -3.55816524e+03  4.55505025e+03  5.38528878e+03 -1.98203131e+03
 -9.07005437e+02 -5.81003371e+03  3.09228199e-11 -2.96818021e+03
 -5.14910929e+03 -1.35720407e+03 -2.50925984e+03 -8.85295621e+02
  6.23324004e+01 -3.97672354e+02  5.30335466e+02  1.10249112e+03
  7.67490874e+02  1.42853257e+03 -4.40979642e+03 -2.26965224e+03
  2.72848411e-12 -7.81344278e+02  9.89875414e+03  7.41203711e+01
  1.72877155e+02 -6.90306317e+02  2.12448560e+02 -2.12678121e+03
 -4.08897762e+03 -5.32234901e+03 -7.26617389e+03 -3.78159479e+03
 -1.73886584e+03 -8.35828037e+02  5.09914580e+03  1.95555334e+02
  3.21079134e+03 -2.70880140e+03  1.85707054e+04 -3.52425642e+03
 -4.07496820e+03 -2.44283284e+03 -5.22353002e+03 -3.99824097e+03
 -1.33211389e+03 -9.61357472e+03 -1.62083940e+03  1.61686579e+03
 -1.41019737e+03 -1.86443018e+03  9.80466530e+02 -2.10574611e+02
  3.65393844e+02 -3.65138060e+03 -3.90357756e+03 -1.74032109e+03
 -2.95419828e+02  3.61082723e+02 -2.12827059e+02  2.26470078e+03
 -1.23126115e+02  1.61302500e+04 -6.81444707e+01  1.75156382e+02
  3.77529982e+02 -2.85863409e+03  1.01491058e+03  2.61206261e+02
 -3.94565286e+02 -3.07453206e+03  3.77757499e+04 -3.44875057e+03
 -4.61324811e+02  6.03133069e+03 -1.28663782e+03 -2.47093745e+02
 -9.36955176e+03 -3.15462950e+03 -1.95929682e+03  1.04787088e+04
 -1.36654650e+03  1.71684653e+02 -2.12102947e+03 -3.52427393e+03
  3.43844920e+02 -2.07359577e+03 -2.24035593e+02  3.90745231e+03
 -4.82065502e+02 -8.86133144e+02 -4.30214951e+03  5.91171556e-12
  5.23042758e+02 -5.26428434e+03  2.79763159e+02 -1.81798392e+03
 -3.85736422e+03 -6.80353725e+02 -2.30824830e+01  5.63842941e+04
 -2.14168867e+03 -1.31203974e+01  5.77166843e+03  3.42932749e+03
 -6.03476439e+02  2.56457064e+03 -2.13209502e+03  0.00000000e+00
 -1.57310963e+03  4.47595136e+02 -4.36514473e+02 -1.11921467e+03
  4.97385089e+02  4.43737153e+01 -5.52271644e+02  5.75106260e+03
  9.39727753e+01  4.36056222e+03  1.20650035e+03 -5.31886908e+02
 -6.24276087e+03  1.90859624e+03 -3.12189558e+02 -2.00088834e-11
 -8.86688411e+02 -7.25566997e+03 -8.54920299e+02  8.12067610e+02
 -1.08002496e-11 -2.71539811e+02 -3.51134621e+03  5.59997253e+03
 -3.68397365e+03  1.19726722e+03 -2.59250590e+03 -2.11035469e+03
  1.24541351e+02 -5.45696821e-12 -1.34761292e+03 -2.37439090e+03
  3.31707598e+02 -6.94008724e+02 -2.12892698e+02 -4.25721518e+03
 -8.03415431e+02 -9.09494702e-12 -4.38875945e+02  1.16995116e+03
 -1.31510496e+03  2.63171098e+03 -1.05991874e+03  4.11884055e+03
  4.44233795e+03  3.66400178e+03 -4.01916585e+03  2.29110464e+03
  3.96489718e+02 -4.49461657e+00 -1.22888403e+03  8.05613124e+02
 -2.72135877e+03 -1.03189341e+03  1.46454399e+03 -4.46143461e+03
 -4.41104551e+03 -9.78798748e+03 -1.39662876e+02 -8.92684762e+02
  3.31650433e+02 -7.13497882e+02  1.77329494e+04 -3.21670584e+03
 -6.37585328e+03 -2.44463636e+03 -1.56817105e+04 -3.04204797e+03
 -3.99041681e+03  3.16936439e+03 -4.98520955e+02 -3.44648771e+02
 -1.68398628e-12 -1.47810861e+03 -1.56093085e+03 -1.29331083e+02
 -9.87787607e+02 -1.70641838e+02 -8.07963084e+02 -1.92587686e+03
  1.89463903e+03 -7.16725383e+03  1.11147843e+03  1.31445291e+03
  1.01355456e+03 -4.38711690e+03  5.82745959e+02 -3.11927488e+03
 -1.87471448e+03 -5.14581646e+03 -5.06468261e+03 -2.62728210e+02
 -6.34267042e+02 -3.59326777e+03  2.68458553e+04 -1.33154031e+02
  5.16559178e+02 -1.12405453e+03 -1.32808648e+03 -5.73756752e+03
 -3.59048737e+03 -2.84255769e+03 -1.31993881e+03  3.63797881e-12
  3.42264055e+03 -2.16882366e+03 -3.45233298e+03 -3.95945717e+03
 -9.63256944e+03 -4.10845312e+03 -5.95944267e+03  2.05738283e+03
  9.80740783e+02 -4.09116337e+03 -2.67619582e+02  3.63797881e-12
 -2.67262895e+03  4.33566053e+02  6.56057486e+03  5.00222086e-12
 -9.96439994e+02  0.00000000e+00 -2.34449642e+03  2.08117759e+03
 -2.64851337e+03  6.20247940e+03  7.28037743e+02 -1.04396204e+03
  5.79246155e+03  8.52847859e+02 -1.93859100e+03 -3.03747466e+03
  1.28932324e+03 -1.38443493e+03 -6.43038880e+02 -1.72666514e+02
  4.01813167e+03 -4.55586425e+03 -6.09946359e+02 -5.62602958e+03
 -1.07925965e+03  1.19371180e-12 -4.08789952e+03 -3.21542832e+02
  9.11650907e+02 -1.87119907e+04  5.18072953e+02  1.03242352e+03
 -1.01305718e+03  3.11585151e+02 -1.30946868e+03  3.77548117e+03
  1.70530257e-13  1.17934562e+03 -7.98059042e+02 -4.65554855e+02
  1.29106803e-15  2.99819071e+02  2.50019523e+03 -4.07612872e+03
  2.25164320e+04  1.69382595e+04 -2.60396528e+04  1.46343046e+04
  3.62963024e+04  9.53674461e+04 -3.85754078e+04  8.75150985e+03
 -8.02524645e+03  4.95638093e+04  1.18517230e+05 -1.82419952e+04
  1.15004879e+04  1.15840343e+04 -1.68478590e+04  2.96891913e+04
  8.42112873e+03  5.39833388e+03 -2.81365335e+03 -6.86239089e+03
  2.35101056e+04  6.90266779e+03  2.12282399e+04  9.96748725e+03
 -5.84092820e+04  1.32730606e+04 -1.11491206e+04  4.20521108e+02
  6.93035862e+03  9.81106331e+03  6.05440213e+03  3.79239295e+03
 -1.49795994e+04 -4.33754456e+02 -3.05232763e+03  2.08799434e+04
  1.31768736e+04 -1.76910745e+03 -1.59254264e+04 -2.97242931e+03
  5.69573190e+03]
intercept_:- 1051475.490141104

In [647]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,root_mean_squared_error,r2_score

In [663]:
print("mean_squared_error:-",mean_squared_error(yp,y_test))
print("mean_absolute_error:-",mean_absolute_error(yp,y_test))
print("root_mean_squared_error",root_mean_squared_error(yp,y_test))
print("r2_score",r2_score(yp,y_test)*100)

mean_squared_error:- 133576376239.39662
mean_absolute_error:- 234407.50526222412
root_mean_squared_error 365481.0203545413
r2_score 53.434005024236264